#
###################################
# Site wide configuration
####################################
#
title: Tu NA
email: tu.nguyeanh.96@gmail.com
description: (Extremal) Graph Theory
url: # the base hostname & protocol for your site
keywords: ["blog", "graph theory", "discrete mathematics", "machine learning"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Hanoi
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: tuna
  avatar: espeon.png
  job: "Undergraduate student in Applied Mathematics"
  bio: ""
  email: tu.nguyenanh.96@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Anhtu07
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
